# Generated by Django 5.0.14 on 2025-08-05 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBConnection',
            new_name='DatabaseConnection',
        ),
    ]
