# Generated by Django 5.0.14 on 2025-08-18 16:45

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_dbconnection_databaseconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
